"""add create gambar

Revision ID: 8d1225119cbe
Revises: 023eae1925ae
Create Date: 2022-10-01 02:22:33.876349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d1225119cbe'
down_revision = '023eae1925ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gambar', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gambar', 'created_at')
    # ### end Alembic commands ###
