"""add datasensor2

Revision ID: f78bbbf6e50d
Revises: 8d1225119cbe
Create Date: 2022-10-01 03:13:47.203555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f78bbbf6e50d'
down_revision = '8d1225119cbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datasensor',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('temp', sa.String(length=60), nullable=False),
    sa.Column('hum', sa.String(length=60), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('datasensor')
    # ### end Alembic commands ###
